Add updated CharacterReset info
Pryaxis/Plugins pull request #37
Opened 2021-05-15 15:49 UTC by moisterrific

due to popular request...i think?

2021-05-22 23:00 UTC, hakusaro commented
@moisterrific will check soon (sorry for delay, etc., update, security, etc)

2021-05-24 20:25 UTC, moisterrific commented
> @moisterrific will check soon (sorry for delay, etc., update, security, etc)

it's ok, no rush

2021-05-29 03:46 UTC, hakusaro requested changes
AutoRegister has been rejected and has failed secure code review. While not introduced by you, it needs to be updated to use a secure method of password generation. The current method is not secure. If it needs to generate passwords, it needs to use a secure PRNG instead of a password formed of composite elements. Currently, the password can easily be obtained by a malicious server.

2021-05-29 04:03 UTC, hakusaro commented on README.md
> +* [NPC Blocker](https://github.com/moisterrific/NPCBlocker2) by [Olink](https://github.com/Olink), updated by [moisterrific](https://github.com/moisterrific)
NPC Blocker is good

2021-05-29 04:11 UTC, hakusaro commented on README.md
> +* [Character Reset (SSC)](https://github.com/bippity/CharacterReset) by [Bippity](https://github.com/bippity), updated by [moisterrific](https://github.com/moisterrific)
Character reset is good (seefnu)

2021-05-29 04:17 UTC, hakusaro commented on README.md
> +* [Ghost](https://github.com/DannyDan77/Ghost) by [DannyDan77](https://github.com/DannyDan77), updated by [moisterrific](https://github.com/moisterrific)
Ghost is good (rh3myj)

2021-05-29 04:30 UTC, hakusaro commented on README.md
> +* [InfiniteChestsV3](https://github.com/Zaicon/InfiniteChestsV3) by [Zaicon](https://github.com/Zaicon), updated by [moisterrific](https://github.com/moisterrific)
InfiniteChests is good (5zjurx)

2021-05-29 04:31 UTC, hakusaro commented
Everything here is good except for AutoRegister. You can update that one if you want, or we can remove it from this PR and just merge the other plugins.

2021-05-30 02:44 UTC, moisterrific commented
pls just merge the others for now, I'll fix AutoRegister later

2021-06-02 02:41 UTC, hakusaro approved these changes

2021-06-02 02:42 UTC, merged