Update SmartRegions
Pryaxis/Plugins pull request #39
Opened 2021-05-29 16:08 UTC by ZakFahey

This version contains this commit: https://github.com/ZakFahey/SmartRegions/commit/10f2ccd2292279bbc2bf6fa7ae65bdfba3bc0c7f , which changes how regions are stored so that regions are properly saved when using the plugin on a multi-server network (there was a bug where adding one region would rewrite the entire database, which with a multi-server setup breaks things when you have one region added on one server and a different region added on another).

2021-05-29 20:05 UTC, hakusaro requested changes
Do you mind updating the Assembly information so that this uniquely identifies itself and provides its version? Unfortunately we've come to need plugins to have something that we can later use in a kill switch for security vulnerabilities. Based on the information in this assembly, it's hard to identify this as SmartRegions.

<img width="738" alt="Screen Shot 2021-05-29 at 13 04 11" src="https://user-images.githubusercontent.com/532647/120083593-8e417980-c07e-11eb-9898-208a688866dc.png">

2021-05-31 16:02 UTC, ZakFahey commented
> Do you mind updating the Assembly information so that this uniquely identifies itself and provides its version? Unfortunately we've come to need plugins to have something that we can later use in a kill switch for security vulnerabilities. Based on the information in this assembly, it's hard to identify this as SmartRegions.
> 
> <img alt="Screen Shot 2021-05-29 at 13 04 11" width="738" src="https://user-images.githubusercontent.com/532647/120083593-8e417980-c07e-11eb-9898-208a688866dc.png">

Done

2021-06-02 02:33 UTC, hakusaro commented
Thanks!

2021-06-02 02:33 UTC, hakusaro approved these changes

2021-06-02 02:34 UTC, merged