Update Crossplay to v1.3
Pryaxis/Plugins pull request #42
Opened 2021-06-15 21:19 UTC by Moneylover3246

2021-06-21 03:51 UTC, hakusaro requested changes
Can you update your assembly version to 1.3.1?

2021-06-24 15:47 UTC, Moneylover3246 commented
The recent commit was most likely the last breaking bug. Everything should be ok now 🎆

2021-06-25 03:15 UTC, hakusaro requested changes
Please version your plugins (do not just simply provide links to versions that work with given terraria versions), so that if we have to tell people to update your plugin, they can do so easily

2021-06-25 19:38 UTC, Marotheit commented
You also misspelled "Download". Figured you'd like to know.

2021-07-03 05:28 UTC, hakusaro approved these changes

2021-07-03 05:28 UTC, hakusaro commented on README.md
> +  * [Download v1.3.3 - Desktop](https://files.catbox.moe/1p1j8r.dll)
1p1j8r ok

2021-07-03 05:28 UTC, hakusaro commented on README.md
> +  * [Download v1.0.0 - Mobile](https://files.catbox.moe/x4sib0.dll)
x4sib0 ok-ish

_cue nothing else matters song_

2021-07-03 05:28 UTC, merged